default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default
  database: jovial_development

test:
  <<: *default
  database: jovial_test

staging:
  <<: *default
  database: jovial_staging

production:
  <<: *default
  database: jovial_production
